const catchErrorAsync = require('../util/catchError');
const db = require('./../model/index');
const userMe = catchErrorAsync(async (req, res, next) => {

  
});
